"use server"
export async function getBatchThumbnails(
  assets: {
    type:
      | "Avatar"
      | "AvatarHeadShot"
      | "GameIcon"
      | "BadgeIcon"
      | "GameThumbnail"
      | "GamePass"
      | "Asset"
      | "BundleThumbnail"
      | "Outfit"
      | "GroupIcon"
      | "DeveloperProduct"
      | "AutoGeneratedAsset"
      | "AvatarBust"
      | "PlaceIcon"
      | "AutoGeneratedGameIcon"
      | "ForceAutoGeneratedIcon"
      | "Look"
      | "CreatorContextAsset"
      | "Screenshot";
    size: string,
    format: "png" | "jpeg" | "webp",
    id: string | number,
  }[],
) {
  const toAdd: Record<string,string> = {}
  if (assets.length > 20) {
    const rest = assets.slice(20,assets.length)
    const res = await getBatchThumbnails(rest)
    Object.entries(res).forEach((group) => {
      toAdd[group[0]] = group[1]
    })
    assets = assets.slice(0,19)
  }
  const response = await fetch(`https://thumbnails.roblox.com/v1/batch`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Accept": "application/json",
    },
    body: JSON.stringify(assets.map((data) => ({
        requestId: String(data.id),
        targetId: typeof data.id === "number" ? data.id : parseInt(data.id),
        type: data.type,
        size: data.size,
        format: data.format,
        isCircular: false,
      
    }))),
    cache: "no-store",
  });
  
  if (!response.ok) {
    throw new Error(
      `failed to get thumbnails (${response.status}): ${await response.text()}`
    );
  }

  const data = (await response.json())
return {...((data.data as { targetId: number; imageUrl: string }[]).reduce<Record<string, string>>((acc, item) => {
  acc[String(item.targetId)] = item.imageUrl;
  return acc;
}, {})), ...toAdd}
}
